### ISSUE TITLE
Should we remove the update strategy section?

### ISSUE THREAD

**Issue by jroper** [lightbend/openshift-deployment-guide#21]
Currently we have an update strategy of:

```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
```

The [default](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#deploymentstrategy-v1-apps) is:

```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
```

As described in the [docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#rollingupdatedeployment-v1-apps), percentages are converted to absolute values by applying to the number of replicas, and then rounding up for `maxSurge`, or rounding down or `maxUnavailable`. This means for 3 replicas, the default is effectively:

```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
```

So leaving out the section and using the default instead means that a rolling update will start one pod at a time, and kill one old pod each time a new pod is started, as opposed to the current configuration which means it will kill one pod initially, and then start two new pods, once either of those has started, it will start the third and kill a second old pod, and kill the third old pod once the next new pod comes up.

I don't think the difference in behaviour really matters, the only thing is whether we want to document this in the guide? I'm leaning towards remove the config, and mention in the guide that by default, deployments use a configurable rolling update strategy, perhaps linking to the docs.
