### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by jroper** [lightbend/openshift-deployment-guide#22]
As I understand it, the only label that we really need/use is the pod `app` label, since there are selectors both in the deployment spec and the service spec that use it. Other than that, I don't think we need them, and in fact our practice of putting an `app` label on everything (ie on deployments and services) seems to be non standard.

Kubernetes actually documents some label best practices [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/), recommending that every resource object defines the following labels:

```yaml
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: wordpress-abcxzy
    app.kubernetes.io/version: "5.7.21"
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress
    app.kubernetes.io/managed-by: helm
```

That's a lot of boilerplate that I don't think we should include in our documentation, people can add that themselves. I think we should remove all non essential labels.
